"""Central product metadata shared by the dashboard and public export site."""

PRODUCT_NAME = "SecPath ProxyPool"
PUBLIC_SITE_NAME = "SecPath Proxy Lists"
VERSION = "1.0.0"
VERSION_LABEL = f"v{VERSION}"
DEVELOPER_NAME = "Mahdi Alemi"
DEVELOPER_CREDIT = f"Developed by {DEVELOPER_NAME}"
REPOSITORY_SLUG = "MahdiAlemi/secpath-proxypool"
REPOSITORY_URL = f"https://github.com/{REPOSITORY_SLUG}"
REPOSITORY_LABEL = f"github.com/{REPOSITORY_SLUG}"
