from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import xlsxwriter

from .core import RankedProxy, ValidationSummary

GROUP_TITLES = {
    "socks5": "Top SOCKS5 Proxies",
    "socks4": "Top SOCKS4 Proxies",
    "http": "Top HTTP / HTTPS Proxies",
}


def build_excel(
    output_path: str | Path,
    *,
    group: str,
    proxies: list[RankedProxy],
    summary: ValidationSummary,
    repository_url: str,
) -> None:
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    workbook = xlsxwriter.Workbook(output)
    workbook.set_properties(
        {
            "title": GROUP_TITLES[group],
            "subject": "Automatically validated public proxy export",
            "author": "SecPath ProxyPool",
            "company": "SecPath",
            "comments": "Generated by SecPath Proxy Lists using the SecPath ProxyPool validation engine.",
        }
    )

    sheet = workbook.add_worksheet("Top Proxies")
    about = workbook.add_worksheet("About")

    title_format = workbook.add_format(
        {
            "bold": True,
            "font_size": 18,
            "font_color": "#FFFFFF",
            "bg_color": "#122033",
            "align": "left",
            "valign": "vcenter",
        }
    )
    subtitle_format = workbook.add_format(
        {"font_color": "#526071", "font_size": 10, "text_wrap": True}
    )
    label_format = workbook.add_format({"bold": True, "font_color": "#233044"})
    header_format = workbook.add_format(
        {
            "bold": True,
            "font_color": "#FFFFFF",
            "bg_color": "#167C80",
            "border": 0,
            "align": "center",
            "valign": "vcenter",
            "text_wrap": True,
        }
    )
    body_format = workbook.add_format({"font_color": "#18212F", "border": 0})
    center_format = workbook.add_format({"font_color": "#18212F", "align": "center"})
    integer_format = workbook.add_format({"font_color": "#18212F", "num_format": "0", "align": "center"})
    decimal_format = workbook.add_format({"font_color": "#18212F", "num_format": "0.0", "align": "center"})
    percent_format = workbook.add_format({"font_color": "#18212F", "num_format": "0%", "align": "center"})
    date_format = workbook.add_format({"font_color": "#18212F", "num_format": "yyyy-mm-dd hh:mm:ss", "align": "center"})
    link_format = workbook.add_format({"font_color": "#167C80", "underline": True})
    note_format = workbook.add_format(
        {"font_color": "#526071", "bg_color": "#F2F6F8", "text_wrap": True, "valign": "top"}
    )

    sheet.set_tab_color("#167C80")
    sheet.set_row(0, 32)
    sheet.merge_range("A1:M1", GROUP_TITLES[group], title_format)
    generated = datetime.now(timezone.utc)
    sheet.merge_range(
        "A2:M2",
        "Fresh public proxies ranked by repeated connectivity checks, reliability, latency, and exit-IP diversity.",
        subtitle_format,
    )

    metrics = [
        ("Generated (UTC)", generated.replace(tzinfo=None)),
        ("Candidates fetched", summary.fetched),
        ("Candidates tested", summary.tested),
        ("Healthy candidates", summary.healthy),
        ("Exported", len(proxies)),
    ]
    for row, (label, value) in enumerate(metrics, start=2):
        sheet.write(row, 0, label, label_format)
        if isinstance(value, datetime):
            sheet.write_datetime(row, 1, value, date_format)
        else:
            sheet.write(row, 1, value, integer_format)

    headers = [
        "Rank",
        "Protocol",
        "IP",
        "Port",
        "Proxy URL",
        "Exit IP",
        "Success Rate",
        "Median Latency (ms)",
        "Jitter (ms)",
        "Remote DNS",
        "Verified Scheme",
        "Checked At (UTC)",
        "Score",
    ]
    header_row = 8
    sheet.write_row(header_row, 0, headers, header_format)
    sheet.set_row(header_row, 28)

    for offset, result in enumerate(proxies, start=1):
        row = header_row + offset
        checked = result.checked_at.astimezone(timezone.utc).replace(tzinfo=None)
        values = [
            offset,
            result.candidate.protocol.upper(),
            result.candidate.host,
            result.candidate.port,
            result.proxy_url,
            result.exit_ip or "",
            result.success_rate,
            result.median_latency_ms or 0,
            result.jitter_ms,
            "Yes" if result.remote_dns else "No",
            result.verified_scheme or "",
            checked,
            result.score,
        ]
        sheet.write(row, 0, values[0], integer_format)
        sheet.write(row, 1, values[1], center_format)
        sheet.write(row, 2, values[2], body_format)
        sheet.write(row, 3, values[3], integer_format)
        sheet.write(row, 4, values[4], body_format)
        sheet.write(row, 5, values[5], body_format)
        sheet.write(row, 6, values[6], percent_format)
        sheet.write(row, 7, values[7], integer_format)
        sheet.write(row, 8, values[8], integer_format)
        sheet.write(row, 9, values[9], center_format)
        sheet.write(row, 10, values[10], center_format)
        sheet.write_datetime(row, 11, checked, date_format)
        sheet.write(row, 12, values[12], decimal_format)

    last_row = max(header_row + len(proxies), header_row + 1)
    sheet.autofilter(header_row, 0, last_row, len(headers) - 1)
    sheet.freeze_panes(header_row + 1, 0)
    sheet.set_column("A:A", 8)
    sheet.set_column("B:B", 12)
    sheet.set_column("C:C", 18)
    sheet.set_column("D:D", 10)
    sheet.set_column("E:E", 31)
    sheet.set_column("F:F", 18)
    sheet.set_column("G:G", 14)
    sheet.set_column("H:I", 18)
    sheet.set_column("J:K", 16)
    sheet.set_column("L:L", 21)
    sheet.set_column("M:M", 11)
    sheet.hide_gridlines(2)

    if proxies:
        sheet.conditional_format(
            header_row + 1,
            6,
            header_row + len(proxies),
            6,
            {"type": "3_color_scale", "min_color": "#FDE2E2", "mid_color": "#FFF1BF", "max_color": "#D7F5E8"},
        )
        sheet.conditional_format(
            header_row + 1,
            7,
            header_row + len(proxies),
            7,
            {"type": "data_bar", "bar_color": "#49A6A8"},
        )
    else:
        sheet.merge_range(
            header_row + 1,
            0,
            header_row + 2,
            len(headers) - 1,
            "No healthy proxies were available in this validation run.",
            note_format,
        )

    about.set_column("A:A", 24)
    about.set_column("B:B", 80)
    about.set_row(0, 32)
    about.merge_range("A1:B1", "About this export", title_format)
    about.write("A3", "Generated by", label_format)
    about.write("B3", "SecPath Proxy Lists", body_format)
    about.write("A4", "Project", label_format)
    about.write_url("B4", repository_url, link_format, repository_url)
    about.write("A6", "Validation", label_format)
    about.write(
        "B6",
        "Each candidate is tested multiple times from a GitHub-hosted runner. Results can differ from another network or country.",
        note_format,
    )
    about.write("A7", "Responsible use", label_format)
    about.write(
        "B7",
        "Public proxies are untrusted infrastructure. Never send passwords, personal data, session cookies, or other sensitive traffic through them.",
        note_format,
    )
    about.write("A8", "Availability", label_format)
    about.write(
        "B8",
        "A successful check is point-in-time evidence only and does not guarantee future availability, privacy, ownership, or safety.",
        note_format,
    )
    about.hide_gridlines(2)

    workbook.close()
